databases:
  - name: postgres
    ipAllowList: []
    databaseName: gibneygunson_production
    user: gibneygunson_production
    # user: my_app_render

services:
  - type: web
    name: gibneygunson
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: <%= ENV["SECRET_KEY_BASE_GG"] %>
        sync: false
