databases:
  - name: postgres
    ipAllowList: []
    databaseName: gibneygunson_production
    user: <%= ENV["GG_DB_USER"] %>
    # user: gibneygunson_production
    # user: my_app_render

services:
  - type: web
    name: gibneygunson-db
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: <%= ENV["GG_DB_HOST"] %>
        fromDatabase:
          name: gibneygunson-db
          property: connectionString
      - key: <%= ENV["SECRET_KEY_BASE_GG"] %>
        sync: false
