databases:
  - name: postgres
    ipAllowList: []
    databaseName: gibneygunson_production
    user: gg_admin

services:
  - type: web
    name: gibneygunson-db
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: ggdbhost
        fromDatabase:
          name: gibneygunsonDb
          property: host
      - key: ggdbuser
        fromDatabase:
          name: gibneygunsonDb
          property: user
      - key: ggdbpass
        fromDatabase:
          name: gibneygunsonDb
          property: password
      - key: secret_key_base
        name: SECRET_KEY_BASE_GG
        sync: false
